### ISSUE TITLE
Deployed documentation different to online version

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#446] opened 2020-06-05 11:13 UTC
Here is the documentation on `readthedocs.io`:
![image](https://user-images.githubusercontent.com/1108513/83870222-c7723280-a725-11ea-9dff-92ef6c6965ff.png)

Here is the documentation that goes into the deployment:
![image](https://user-images.githubusercontent.com/1108513/83870249-d2c55e00-a725-11ea-8c42-c643e54825df.png)

Is the deployed version of documents deliberately a smaller subset?   If it is, we need to add the `Importing initial reference data` section.

**Comment by robintw** [comment] 2020-06-08 10:36
This was actually an issue caused by trying to find the docs on OS X when it had been build on Windows. Closing.

**Closed by robintw** 2020-06-08 10:36 UTC
