### ISSUE TITLE
Tidily handle authentication error

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#331] opened 2020-04-13 14:10 UTC
I made a mistake in my `.ini` config file, I put the wrong parameter in as db_username for a postgres database.

Pepys_Import fell over. That's ok - it couldn't log in.  But, it showed an untidy stack trace for this quite common/likely error.

I'd like us to provide a tidy, succinct feedback that password authentication failed.   We should tidily handle it in both `import` and `admin`, please.

Here's the stack trace:
```
python -m pepys_import.import --path tests/sample_data/track_files/
   @@@@ @@@@@        ______                      _                            _   
 @@@@@ @@..@@@@      | ___ \                    (_)                          | |  
  @@@     @@@@@@     | |_/ /__ _ __  _   _ ___   _ _ __ ___  _ __   ___  _ __| |_ 
  @@@     @@@@@@@@   |  __/ _ \ '_ \| | | / __| | | '_ ` _ \| '_ \ / _ \| '__| __|
 @@@@.     @@@@@@@   | | |  __/ |_) | |_| \__ \ | | | | | | | |_) | (_) | |  | |_ 
 @@ #@@ @   ...@@@@@ \_|  \___| .__/ \__, |___/ |_|_| |_| |_| .__/ \___/|_|   \__|
 @@   &        @@@@@            | |     __/ | ______          | |                   
Software Version :  0.0.9 


Database Type :  postgres
Database Name :  pepysdb_dev
Database Host :  postgresql-pepysdb.alwaysdata.net
-------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 481, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "pepysdb_core"
FATAL:  password authentication failed for user "pepysdb_core"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ian/git/pepys-import/pepys_import/core/store/data_store.py", line 137, in initialise
    with self.engine.connect() as conn:
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2206, in connect
    return self._connection_cls(self, **kwargs)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2306, in raw_connection
    self.pool.unique_connection, _connection
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
    e, dialect, self
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 481, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "pepysdb_core"
FATAL:  password authentication failed for user "pepysdb_core"

(Background on this error at: http://sqlalche.me/e/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ian/git/pepys-import/pepys_import/import.py", line 80, in <module>
    main()
  File "/Users/ian/git/pepys-import/pepys_import/import.py", line 36, in main
    process(path=args.path, archive=args.archive, db=args.db, resolver=args.resolver)
  File "/Users/ian/git/pepys-import/pepys_import/import.py", line 69, in process
    data_store.initialise()
  File "/Users/ian/git/pepys-import/pepys_import/core/store/data_store.py", line 141, in initialise
    raise Exception(f"Error creating database({self.db_name})! Quitting")
Exception: Error creating database(pepysdb_dev)! Quitting
```

**Comment by BarisSari** [comment] 2020-04-13 14:28
@robintw's exception handler will catch this error (https://github.com/debrief/pepys-import/pull/322/). I'll reproduce the error once it's merged to the `develop`. Then, we can think of possible changes for catching the Authentication Error specifically if necessary. Does it make sense, @IanMayo?

**Comment by IanMayo** [comment] 2020-04-13 15:07
Yes, good plan.

**Comment by BarisSari** [comment] 2020-04-14 12:45
Because of this line, I was assuming that this error will be caught but it didn't:
`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "pepysdb_core"
FATAL:  password authentication failed for user "pepysdb_core"`

This error and (https://github.com/debrief/pepys-import/issues/332) means that we should catch common `psycopg2` errors as well. I'll work on that.

**Comment by robintw** [comment] 2020-04-14 12:48
That's really strange, I was checking for a `sqlalchemy.exc.OperationalError`...I can't understand why it wasn't catching it.

If we're catching loads and loads of errors maybe we should write a utility function that does the checking and use that for both the pepys_admin and pepys_import CLI exception handlers (or maybe just a constant defined somewhere that defines what exceptions we're looking for?)

**Comment by IanMayo** [comment] 2020-04-14 12:51
Aah, @robintw - it's most likely I was running from `develop`, and your checking isn't in `develop` yet.

**Comment by BarisSari** [comment] 2020-04-14 12:52
Yes, it's strange. I'm actually thinking whether we can catch these `psycopg2` errors in data_store.py instead of pepys_admin or pepys_import. Because they are connection errors and we can catch them during the DB connection.

**Comment by IanMayo** [comment] 2020-04-14 13:02
> catch these psycopg2 errors in data_store.py instead of pepys_admin or pepys_import

Ooh, good thinking @BarisSari

**Closed** 2020-04-14 16:54 UTC
