### ISSUE TITLE
Problem moving snapshot between databases

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#1121] opened 2021-12-17 15:30 UTC
## Version

0.0.35

## 🐞 Description

Analysts are experimenting with how they would run Pepys across two disconnected networks.  For the trial, they did this:
* create two MS-Windows VMs
* install postgres on each VM
* load a track into VM1 using pepys-admin
* export a snapshot of all data for the year when the track happened
* move the snapshot to VM2
* try to load the snapshot into the VM2

The analyst (MH) reported that the import got to 18% before Pepys crashed, citing a Python error.

We won't be able to get a log of the output until the New Year.

We should try to reproduce the above.  Note: I guess we could use `tracstor` as the donor database (VM1), and a locally install of postgres as VM2.

**Comment by robintw** [comment] 2022-01-04 21:23
I think this is basically the workflow that I tested before we released that functionality - so it should all work.

The problem sounds like a problem with the merging of snapshots - if we have the Python error sometime once they're back at work then we can investigate.

**Comment by IanMayo** [comment] 2022-01-12 11:20
I have inquired about any stack-trace, but apparently they're not available.
```
The command prompt (Pepys Admin) only shows:

        Merging reference tables
        18% | 'progress bar' |3/17 [00:02<00:14,        1.06s/it]

Before a pop up window saying Python has stopped working - please close the program.

Then the command prompt says Press any key to continue ...
```

**Comment by robintw** [comment] 2022-01-12 16:44
Wow, that's weird.

This is actually Python itself crashing (possibly with something serious like a segfault) and Windows picking up the pieces and giving us an error message.

I'm not really sure how to proceed from here as I don't know how we can get the information we would need to debug what was going on. It'd be a lot easier if I could have the data files that they're trying to merge, but I assume they're all sensitive data.

We could look up which reference table is 3rd in the list of tables to be merged, and someone could look at the data on site to see if there is anything weird in those tables - but beyond that I'm not really sure what to do.

Presumably they're merging tables that were created with the same Pepys version? Something like a segfault would suggest some sort of binary library incompatibility...

What do you think?

**Comment by IanMayo** [comment] 2022-01-13 12:43
How about we "instrument" a copy of Pepys, outputting debug lines to help us get to the point where Python crashes?

I've asked to OP how long it takes before the crash happens. If it's 10s of seconds, then it could be out of memory.

**Comment by IanMayo** [comment] 2022-01-26 08:53
More detailed steps to reproduce:

* Two instances of Pepys on separate VMs:
    * PostGres 12.6
    * PostGIS Bundle
    * Setting a local CONFIG file  as the environment variable pointing to the local database.
    * Pepys
    * PG Admin (is part of the postgres install).
* I uploaded one version of Pepys with narrative and Tracks from Nelson and the other with Track from Collingwood using the debrief sample rep files
* I created a snapshot based upon time (I think from the day before the track to the day after) to covering the whole of the track & created a snapshot. 
* I moved this snapshot to the other VM and tried to merge the other instance of Pepys when it crashes.

**Comment by IanMayo** [comment] 2022-02-02 12:48
Reproducing error.

Steps to reproduce:
- from database instance with just one track, go into `Snapshots` & `Create snapshot with all data`
- from second database, go into `Snapshots` & `Merge databases`
- select exported SQLite snapshot
- confirm happy to perform merge
- "Merging reference tables"
- Progress counter jumps to 12%
- Progress counter jumps to 18%
- Windows dialog opens, reporting "Python has stopped working".  Instruction to "Close the program".
- Click on "Close the program" and command prompt has "Press any key to continue".

Diagnosis:
- find "Merging reference tables"
- Find loop to export each table
- insert line to `print("Merging " + ref_table)`

Pepys runs through:
- Merging reference tables
- Merging GeometryType
- Merging ForceType
- Merging PlatformType
- Merging Nationality
- Crash happens.

**Comment by robintw** [comment] 2022-02-02 19:06
This is _really, really_ weird. The line that it is crashing on is just doing a SQLAlchemy query - it's not trying to write results back to the database or anything, it's literally just a simple query with a WHERE clause:

```
results = (
                    self.slave_store.session.query(self.slave_store.db_classes.Synonym)
                    .filter(self.slave_store.db_classes.Synonym.entity == from_id)
                    .all()
                )
```

We're inside the `session_scope` so we're not accessing anything relating to the session that might have been deleted or anything.

I'm really not sure where to go from here. There's nothing I can really do to that line of code to do things differently - we need to do that query.

Annoyingly, this error will occur even if there aren't any synonyms for Nationalities in the database, as it is occurring in the code that is checking to see if there are any synonyms for the Nationalities that have been updated. So we can't even just tell them not to use synonyms for that table.

I don't understand why this is occurring for Nationalities but not for PlatformTypes, where the same code would be run and the same process occurring. Similarly, I don't see why it fails at Nepal, but then if that is deleted it continues for a few rows, and then fails again.

The only suggestions I have at this stage are:

- When you got the Windows error message saying that Python had stopped working, are there any extra buttons that might give you access to some sort of stack trace or core dump? I presume not, but I wanted to check.
- We could provide a new release to them which has been created with the latest versions of all the dependencies: SQLAlchemy has had a number of bug fix releases in the last few months (see [here](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#changelog)). I've scanned through quite a bit of that page, and none of them seem particularly relevant - but it's probably worth trying.
- We could raise an issue on the SQLAlchemy repo as it seems to be occurring in SQLAlchemy code. I'm not sure they'd be able to do much without some sort of stack trace, and also they'd expect us to be using the latest version before doing that.

Have you tried to reproduce this on your Windows machine/VM? I can try on Windows later in the week and see if I can reproduce - it'll definitely be a lot easier to debug if we can reproduce it on some machine that we control.

I'm afraid those are all my thoughts for now - sorry I can't be more help

**Comment by robintw** [comment] 2022-02-02 20:06
Ah also - do you know exactly which version of Pepys they're running on-site? When I test with Windows at home I'd like to test the same version.

**Comment by IanMayo** [comment] 2022-02-03 08:33
> I don't understand why this is occurring for Nationalities but not for PlatformTypes, where the same code would be run and the same process occurring. Similarly, I don't see why it fails at Nepal, but then if that is deleted it continues for a few rows, and then fails again.

One difference is the size of the table.  Nationalities is a lot longer than PlatformTypes.  According to [this list](https://www.worldometers.info/geography/alphabetical-list-of-countries/) Nepal is 122nd.  From seeing their data they have to `Netherlands` countries - so their list may be longer.  Hmm, `122` is close to `128`.    It did seem significant that deleting one nation lead to two more being listed.  Then deleting two more nations lead to four more being listed.  Well, significant but strange.

> Ah also - do you know exactly which version of Pepys they're running on-site? When I test with Windows at home I'd like to test the same version.

They're on 0.0.35, dated 16th December 2021.

> When you got the Windows error message saying that Python had stopped working, are there any extra buttons that might give you access to some sort of stack trace or core dump? I presume not, but I wanted to check.

No. I also tried pressing <ctrl-c> just before the point where it was failing, but it didn't give a stack trace.

> We could provide a new release to them which has been created with the latest versions of all the dependencies: SQLAlchemy has had a number of bug fix releases in the last few months (see here). I've scanned through quite a bit of that page, and none of them seem particularly relevant - but it's probably worth trying.

Yes. Given that it's most likely the issue lies outside our code then updating the up-stream dependencies seems like a wise thing to do next.

> We could raise an issue on the SQLAlchemy repo as it seems to be occurring in SQLAlchemy code. I'm not sure they'd be able to do much without some sort of stack trace, and also they'd expect us to be using the latest version before doing that.

_Maybe_ it would be possible to produce a minimum-reproducible-example.  But, as you said - let's get our dependencies upgraded first.  To be honest, that should probably include Postgres, too.

**Comment by robintw** [comment] 2022-02-03 11:00
Yes, I think dependency upgrades are a very good idea. I seem to recall they're on a very old version of Postgres, and a fairly old version of PostGIS. There have been significant speed improvements in new versions of both of those - so there should be some other benefits to upgrading.

Also, I've had some inspiration today about another experiment we could do to narrow down where the crash is occurring. I suspect that SQLAlchemy itself isn't causing the crash - as it's nearly all pure Python - but the crash could be in the driver that we're using to connect to the Postgres database. That is called psycopg2, and is compiled C code.

We could switch (temporarily) to using the pg8000 driver which is pure Python. It will be slower than psycopg2, but shouldn't cause a segfault because it's just Python code. If this change worked then we'd be able to raise a bug with psycopg2 and see if we can work on the problem with the maintainers (I sponsor the maintainer of psycopg2 on Github, so we may have a good response from him).

Luckily, the pg8000 driver should be installed in the deployed version anyway, as we use it for some tests (no, I don't know why - it was before my time!). So, to test this it should be as simple as changing line 144 in data_store.py from:

```
            driver = "postgresql+psycopg2"
```

to 

```
            driver = "postgresql+pg8000"
```

and then removing one of the psycopg2-specific options we use, by removing `executemany_mode="batch"` from line 171, to make it read:

```
self.engine = create_engine(
                    connection_string, echo=False, future=True
                )
```

Do you think it would be worth trying that modification on-site @IanMayo?

**Comment by IanMayo** [comment] 2022-02-03 11:23
Great thinking @robintw - will try it tomorrow.  I'll keep you updated.

> I sponsor the maintainer of psycopg2 on Github, so we may have a good response from him

What goes arround, comes around 😀

**Comment by robintw** [comment] 2022-02-03 20:07
Having had a look at a few of the dependencies tonight, we could do with updating various dependencies a bit: SQLAlchemy, psycopg2 have both had quite a few minor releases recently. Pint is also pinned to a version for no particular reason.

I'll create a PR sometime with updates to those and we can check all the tests go ok.

**Comment by IanMayo** [comment] 2022-02-03 21:01
Sure - but I'll try the alternate driver tomorrow.  Could i also try merging into a SQLite instance?

**Comment by IanMayo** [comment] 2022-02-04 12:21
One discovery @robintw .  When I try to merge the snapshot into a SQLite database it still works.  I'll try using the alternate Postgres driver - but the above seems to indicate it's a SQLAlchemy issue.

Aaah, I'll also try to break down the composite SQLAlchemy query - just in case I can isolate the specific step that breaks.

**Comment by robintw** [comment] 2022-02-04 12:39
Interesting. That would actually suggest to me that it _is_ a problem with the Postgres driver. SQLAlchemy is being used whether it is connecting to SQLite or Postgres, the only difference is which driver SQLAlchemy uses.

Definitely trying the Postgres driver will be good, and breaking down the query sounds sensible.

If you want to discuss this while you're on site then feel free to call me, you've got my number. I'm up at the wheelchair shop and on my mobile at the moment, but can take your call here or when I'm driving home.

**Comment by IanMayo** [comment] 2022-02-04 12:56
Damn - sorry.  Guess the linguistic error in my report.   Should have said:
> When I try to merge the snapshot into a SQLite database it still **fails**.

Aah, but.  It gets to the end of the list of nationalities - where there is an `Unknown` nation.  Hmm, maybe it's failing a little later on in SQLite.  More diagnostics required,  Ok. In SQLite it fails in `update_logs_table` - failing at the step to get matching log data for the `Nationality` of `Rwanda`.  The code fails during the `results = ` call in the update-logs-table method.

Ok, changing the driver didn't fix it.  But, given that it now seems to be SQLAlchemy rather than SQLite then that's no surprise.

Back to PostGres.  I've tried breaking down the query, using:
```
  res1 = self.slave_store.session.query(....)
  res2 = res1.filter(....)
  results = rse2.all()
```

 It will run:
- query
- filter

But, if fails on `res2all()`.  It also fails if I try to use `print(res2.count()`.

**Comment by robintw** [comment] 2022-02-04 21:10
The good news is that I've managed to reproduce this on my Windows machine. Well, on my Windows machine I don't actually get the error saying 'Python has experienced a problem' - but Python just stops and I get returned to the command prompt. So, same sort of thing.

I'm trying various debugging approaches, some of which are proving useful and some of which aren't!

It definitely seems like it is crashing somewhere in SQLAlchemy - the question is where, and whether we can create a minimal example that we can send to the SQLAlchemy devs.

**Comment by robintw** [comment] 2022-02-04 21:50
Some (rough, incomplete) notes on the debugging I've been doing:

(I will edit this to update, so view the web version rather than an email to see my latest notes)

**How to reproduce:**
1. Run Pepys Admin using the `--db` option to specify a database called `local.db`, and populate reference and metadata.
2. Run Pepys Admin again using `--db` to specify a database called `remote.db` and populate reference and metadata.
3. Run Pepys Admin using `--db` to specify `local.db` and choose to merge in `remote.db`.
4. Crash occurs.

The crash happens when merging log entries for Nationalities. It happens within the SQLAlchemy query `.all()` call. It happens _before_ the SQLAlchemy logging occurs when `echo=True` on the engine.

Crash seems to be occurring inside code in `C:\pepys-deploy\pepys-import\python\Lib\site-packages\sqlalchemy\engine\base.py`. Specifically, the code gets to `Connection.__init__` line 98 - where it calls `engine.raw_connection()`, and then crashes there.

On the client's machines it gives an error saying `Python has experienced a problem`, on the developer's machine it just stops and drops back to the command prompt.

I thought this might be an issue with SQLAlchemy 1.4 (which was a pretty big release), but it seems to occur in v0.0.25 of Pepys, which was the last version _before_ the SQLAlchemy upgrade. I am going to test an older version too.

I thought we would have had tests that covered exactly this situation, but it seems not. I will write a test for this specific situation and check that it fails.

**Comment by robintw** [comment] 2022-02-04 22:16
Ok, things are a bit weird but...I think I may have fixed the bug.

I found that if I commented out the _rest_ of the function (ie. the bit _after_ the query that was crashing) then the query stopped crashing. Weird! (I assume that because it's in a loop, the code at the end of the loop can affect the next iteration of the loop). Anyway, I then realised that the code below that query in the loop was not written quite right: it should have worked, but there was a more efficient and sensible way to write it. And, changing it to this more efficient way worked.

Basically what we were doing was adding a load of empty lists (calling `session.add_all([])` in effect) because the code was like this:

```
# Search for it in the Logs table
                results = (
                    self.slave_store.session.query(self.slave_store.db_classes.Log)
                    .filter(self.slave_store.db_classes.Log.id == from_id)
                    .all()
                )

                if len(results) > 0:
                    # If it exists, then modify the old ID to the new ID
                    for result in results:
                        result.id = to_id

                # Commit changes
                self.slave_store.session.add_all(results)
                self.slave_store.session.commit()
```

That is, the `add_all` and `commit` calls were being run regardless of whether `results` was an empty list, or whether it had contents. I've now changed this by indenting the last two lines so that they come within the if statement:

```
# Search for it in the Logs table
                results = (
                    self.slave_store.session.query(self.slave_store.db_classes.Log)
                    .filter(self.slave_store.db_classes.Log.id == from_id)
                    .all()
                )

                if len(results) > 0:
                    # If it exists, then modify the old ID to the new ID
                    for result in results:
                        result.id = to_id

                    # Commit changes
                    self.slave_store.session.add_all(results)
                    self.slave_store.session.commit()
```

I have no idea what's going on here: I suspect it may be some sort of resources issue. Windows is generally more picky about resource limits than Linux/Mac, and possibly trying to commit all the time, even with empty lists, was causing something strange to happen with resources.

I don't 100% believe that I've fixed this, so my plan is to:

1. Let my brain ponder this over the weekend (or at least, most of the weekend)
2. Write a test to test the exact situation which caused the crash
3. Try and reproduce this in a standalone file which does a load of `add_all` calls with empty lists and see if I can get it to crash
4. If I can reliably reproduce it, then raise a bug with SQLAlchemy. Obviously it's not something you should be doing, but it's also something that shouldn't cause a segfault/crash.

So in summary: probably fixed, all a bit strange, will do some more work on it.

**Comment by robintw** [comment] 2022-02-04 22:19
(Actually it may be the `commit` calls that are causing the problem, not the `add_all` calls)

**Comment by robintw** [comment] 2022-02-07 19:41
I've sort-of managed to reproduce this in a simple bit of example SQLAlchemy code (outside of Pepys). The following code causes a crash around iteration 530. However, when running this code we get an Exception from SQLAlchemy, as opposed to just crashing which is what happens in our code. I've had a long play with this minimal code to try and get it to fully crash rather than giving an exception, but I can't manage to get it to do that.

The exception raised is: `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) A dynamic link library (DLL) initialization routine failed.`, which I think is referring to the spatialite DLL that we load when creating a new connection

I suspect any bug report to SQLAlchemy would get closed as a non-issue because a) you shouldn't run commit a load of times in a loop when you're not doing anything that needs committing and b) you get an exception raised anyway in this example (even if it is a rather weird exception, and doesn't really make sense). Do you think it's worth raising an issue with them @IanMayo?

The code is below:

```python
from sqlalchemy import create_engine, func, select, text
from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import sessionmaker, scoped_session
from sqlalchemy.event import listen

Base = declarative_base()

class User(Base):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)
    name = Column(String)
    fullname = Column(String)
    nickname = Column(String)

def load_spatialite(connection, connection_record):
    connection.enable_load_extension(True)

    connection.load_extension("mod_spatialite")

engine = create_engine('sqlite:///test_crash.db', echo=False)
listen(engine, "connect", load_spatialite)

Base.metadata.create_all(engine)

db_session = sessionmaker(bind=engine)

session = db_session()
for i in range(1000):
    print(i)
    results = session.query(User).first()

    session.commit()
```

(I haven't yet managed to reproduce the crash with Postgres with a minimal example)

**Closed** 2022-02-08 09:07 UTC
Labels: bug

**Comment by IanMayo** [comment] 2022-02-08 09:10
> Do you think it's worth raising an issue with them @IanMayo?

Yes please @robintw . You're welcome include your caveats above, but at least the issue (and solution) will be documented in the repo - and may help the next SQLAlchemy consumer.
