### ISSUE TITLE
pepys."Tasks" table - Self-Referential design

### ISSUE THREAD

**Issue by arunlal-v** [debrief/pepys-import#839] opened 2021-03-29 21:47 UTC
**pepys."Tasks"** table has a self-referential design (popularly known as Adjacency list anti-pattern in SQL Designs). Self-referencing table design is [considered as a design anti-pattern for the below reasons.](https://www.slideshare.net/billkarwin/sql-antipatterns-strike-back/51-Naive_Trees_Adjacency_List_Naive)

1) For tree like data structure represented by Adjacency list, the operations on the nodes cannot be done independent of the edges. In other words, two logically different functions (DML on Task definitions, and DML on Task relations) rely on the same table. 

2) Join operations for tree querying has to process the Task definition each time.

3) Cascading deletes cannot be specified as they might induce a recursive sequence of deletes. 

4) Depth of tree has to be hard coded into the query. *This issue is invalidated by the SQL-99 standard, which defines recursive query syntax using the WITH keyword followed by a common table expression. And currently, Sqlite and Postgres have implemented this standard/feature.*

One commonly cited design pattern to implement tree data is the [Closure tables](https://www.slideshare.net/billkarwin/sql-antipatterns-strike-back/68-Naive_Trees_Solution_3_Closure).  Closure tables also allows for many-to-many relationships. Should we consider redesigning **pepys."Tasks"** using this?

If the recursion depth is going to be static, i.e. only 3 levels of depth is allowed, then can we change our table design to reflect this instead of going for a recursive structure? This will make sure that only one task id column is present and the other two levels are just their corresponding level 2 and 3 attributes.

**Comment by robintw** [comment] 2021-03-30 08:43
Thanks @arunlal-v. Interesting question - and now is definitely the right time to consider it (before the users have a load of Task entries). I'm not 100% sure that switching how we store Tasks is the right thing to do, but it has also raised a number of interesting relevant questions in my mind, so it's definitely worth thinking about. I've had a few thoughts which I'll try and jot down sometime - but this week I'm involved in a conference full-time, so won't have much time to work on this. I'll be able to provide a full response next week.

**Comment by IanMayo** [comment] 2021-03-30 10:24
The article was an interesting read @arunlal-v 

It's important that @Robin & I understand the idea.  I _think_ the change would extend to Platforms and Participants.

We have these concepts for Tasks:
- Level one is just a name.  Those _could_ move to another simpler table: `TaskGroups`
- Level two has participants, and start/finish date
- Level three has participants (taken from subset of level 2 list), plus start/finish date

It may be a good idea to create a SQLFiddle-playground demo table, showing the new structure, some sample data, plus how we would run queries against it.

**Comment by arunlal-v** [comment] 2021-03-30 17:31
Here's a first demo: http://sqlfiddle.com/#!17/3d6e9/5

Let me know if any other scenarios are to be included.

*P.S.: The queries demonstrated in the fiddle can be achieved, even though a little cluttered, using Adjacency list table design as well.*

**Comment by arunlal-v** [comment] 2021-03-31 20:45
Based on analysis of data in **pepys.Tasks** table, the details shared in [issue 840](https://github.com/debrief/pepys-import/issues/840) and [in this thread](https://github.com/debrief/pepys-import/issues/839#issuecomment-810105895), and my discussion with @IanMayo, I think we can remodel the **Tasks** and its related tables **without recursion.**

Consider this design: http://sqlfiddle.com/#!17/876ed3/1

I believe this closely resembles real life war game series. The **Tasks** table in the new design can be enhanced to include iteration details of the war game series (or the iteration can be arrived upon based on calculated rank after sorting all tasks of a given task_group by year), but those are finer points that we can consider later.

This design can also handle ad-hoc war games that do not belong to any series, like a joint US-Japan war game in response to an aggressor in the South China Sea.

This design eliminates 
* the need to save start date and end date for the level 1 tasks in the current design
* the need to introduce "Participant" (solely for tasks) as it maps "Platform" and "Task" under "Participation"

**Comment by arunlal-v** [comment] 2021-03-31 20:51
@IanMayo, @robintw, please let me know if there are any scenarios that cannot be handled by the [new design](http://sqlfiddle.com/#!17/876ed3/1).

**Comment by IanMayo** [comment] 2021-04-01 07:51
Thanks @arunlal-v,
couple of items of feedback:
1) We can't use the term `task_group`, since it already has meaning in my user domain https://en.wikipedia.org/wiki/Task_Group
2) I'm sure the users need the two levels of tasks.  Let me mock structure:
- Joint Warrior
    - JW 20/01 _first exercise of 2020_
        - J05090 _wargame on 5th day of month, given index `090`_
        - J05110 _wargame given index `110`, to allow for others to be created between it and `130`_
        - J05130
        - J05150
        - J05180
        - J06090 _wargame on 6th day of month, given index `090`_
        - J06110
        - _[around 40 more entries for JW 20/01]
    - JW 20/02 _second exercise of 2020_
        - J06090 _wargame on 6th day of month, given index `090`_
        - J06110 _wargame given index `110`, to allow for others to be created between it and `130`_
- Strike Warrior
    - SW 20/01
- Misc
    - PASSEX 20/06
    - ADEX 21/02
       
       
As you'll see, we can't put all of those `J05090` entries under `Joint Warrior`. The indexes are only unique within that particular wargame (`JW 20/01`).

Let me introduce a naming convention for the tiers:
1. Series
2. Wargame
3. Serial

The presence of `JW 20/01` also helps create/maintain the lower level.  The analysts receive a document listing all the ships (participants) in a wargame.  They add it to the wargame as participants. Then as they are adding the serials, they only have to select participants from the limited list defined for the wargame.

 @arunlal-v - I'd appreciate you updating the SQLFiddle to reflect the above data model.

**Comment by arunlal-v** [comment] 2021-04-01 17:36
Considering the review comments, this is how the **Tasks** module should be designed.
This is a long form version of the design. Once this is finalised, we can move into ER Diagrams and SQLFiddles.

**"Exercises"** should be the central point. (In our example, JW 20/01 is an exercise)
An exercise, in Debrief parlance, is comprised of a set of **"Games"** (J05090, J05110, etc. are examples of games)
An exercise has a non empty set of **"Participants"** (ex. Ships, Aircrafts etc.)
A game in a given exercise involves **"Participation"** from only the set of participants mapped for that exercise.
An exercise may be part of a **"Recurring Series"** (In DB terms, it will be represented by **"Series"** and **"Series_Events"** tables)

The following are the advantages of using a *[normalized](https://en.wikipedia.org/wiki/Database_normalization)* structure, like above, instead of a self-referential table with a generic structure to capture disparate attributes.

1) The front end (having different input forms and filters to capture information about different modules like **Exercises**, **Games** ) has to maintain and process the recursion logic each time it has to store any entity data to the table, as each entity is in the same table with different levels of recursion. In case of the normalised design, the front end just has to update specific table to save specific information without any additional logic

2) It helps to extend the application with new functionality, if required. A new feature like **Track the next games** can be based off of just the **Exercises**/**Games** entity (in the new design) and a new events table, if required. This implementation will be complex if the self-referental design of **Tasks** is used as it has join the entire Tasks table containing information about exercises, games, and series. Another new feature like tracking **Ground Rules** (ex. Warships can only use 'n' number of torpedo simulations, etc.) can be introduced just by creating new tables and referencing them in either **Participant**/**Participation** entities (in the new design), instead of referencing from the entire tasks table.

**Comment by IanMayo** [comment] 2021-04-01 18:28
Thanks @arunlal-v  - have renamed `games` to `serials`.

**Comment by arunlal-v** [comment] 2021-04-01 19:15
Here's the SQLFiddle: http://sqlfiddle.com/#!17/9dcc4/5

**Comment by arunlal-v** [comment] 2021-04-01 19:22
Changed **Series_Events** to **Series_Exercises**

**Comment by arunlal-v** [comment] 2021-04-01 20:15
Updated SQLFiddle with name of **Participants** and **Participations** changed to **Exercise_Participants** and **Serial_Participants** respectively.

http://sqlfiddle.com/#!17/89161/4

**Comment by arunlal-v** [comment] 2021-04-02 16:31
Please find below updated long form factoring in the [name changes](https://github.com/debrief/pepys-import/issues/839#issuecomment-812147012)

**"Exercises"** are the central point in *Debrief* to analyze war games. 
An *exercise*, in *Debrief* parlance, is a logical collection of games or **"Serials"**.
An *exercise* has a set of participants called **"Exercise Participants"**  (ex. Platforms like Ships, Aircrafts etc.)
A *serial* in a given exercise has a set of participants called **"Serial Participants"** which is always a subset of *exercise participants* mapped to the given *exercise*.
An *exercise* may be part of **"Series Exercises"** which is a logical set of *exercises* tracked under a **"Series"**.

**Comment by arunlal-v** [comment] 2021-04-02 18:09
@IanMayo, as per the above, a platform that takes part in a serial will have more than one entry in **"Serial Participants"** for a given serial (i.e. more than one *serial_participant_id* for the same *exercise_participant_id*, *serial_id* combo)  based on the duration during which it was active. **"Serial Participants"** also has *start* and *end* attributes which is not the case with **"Exercise Participants"**. So should we rename **"Serial Participants"** to **"Serial Participation"**?

**Comment by arunlal-v** [comment] 2021-04-03 08:36
This is the [*ER diagram*](https://en.wikipedia.org/wiki/Relational_model) for the new structure. (Privacy fields and other metadata attributes are to be added)

![ERDiagram](https://user-images.githubusercontent.com/77854924/113473084-0592cc80-9485-11eb-9857-6efa07ef00de.png)

**Comment by robintw** [comment] 2021-04-03 08:58
I'm busy with childcare today, and won't be able to look at this properly until Tuesday (Monday is a public holiday in the UK). However, in general I like the new approach. I've got a couple of questions based on the ER diagram though:

1. Why does the `series_exercises` table exist? Can't we just have a `series_id` field in the `exercises` table? That would remove one extra layer of tables, and make it easier for me to query the exercises that are part of each series (particularly as doing queries with lots of joins can get complicated with SQLAlchemy). I thought these sort of 'intermediate tables' were only needed when there was a many-to-many relationship, but (as I understand it) each series can have multiple exercises, but each exercise can only be in one series.

(I think I've got another question about `exercise_participants`, but I need to have a bit more of a think about that).

**Comment by arunlal-v** [comment] 2021-04-03 09:23
No issues @robintw. Enjoy your long weekend :) 

1. It's because there could be *exercises* that are not part of any *series* like **PASSEX 20/06** and **ADEX 20/01**. The new design makes *exercises* independent of any *series*. Based on whether the *exercises* are part of a series, these two tables (*series* and *series_exercises*) can be joined to the query or ignored. The relationships can be restricted using constraints. ```each series can have multiple exercises``` is handled in the design. ```each exercise can only be in one series``` can be enforced by a unique key constraint on *series_exercises.exercise_id*. But your suggestion: ```Can't we just have a series_id field in the exercises table?``` is also valid. We'll have one less table to join, but there will be null values for *exercise.series_id* for *exercises* that are not part of any *series*. We can discuss further when you're back.

**Comment by robintw** [comment] 2021-04-06 08:42
Thanks @arunlal-v.

In response to 1) - yes I think that it would be better to remove the `series_exercises` table and just have an `exercise.series_id` field which can be null if the exercise isn't associated with a series. That will work best with the way that I'm dealing with database objects in the UI.

My next question is about why we need both `serial_participants` and `exercise_participants`, and why `serial_participants` references `exercise_participants`. Could we not just have a `participants` table (like we do currently) and reference that from both `exercises` and `serials`? It would mean we just had a table of participants where the ID was either a serial ID or an exercise ID, and then it referenced the platform etc.

I also don't quite understand what you said above:

> a platform that takes part in a serial will have more than one entry in "Serial Participants" for a given serial (i.e. more than one serial_participant_id for the same exercise_participant_id, serial_id combo) based on the duration during which it was active.

Why would there be more than one entry in Serial Participants? Is that just if it is active for various distinct time periods? (eg. 09:00-11:00 and then 15:00-18:00) - I don't know whether this actually happens - @IanMayo, is this something we need to support?

Just as a final comment: it might be useful to extend the SQLFiddle a bit to include some more entries in the data so we can see more easily how this works for various more complex situations. For example, adding an exercise that has no series, adding multiple platforms assigned to different exercises/serials, with different durations etc.

**Comment by arunlal-v** [comment] 2021-04-06 09:40
```In response to 1) - yes I think that it would be better to remove the series_exercises table and just have an exercise.series_id field which can be null if the exercise isn't associated with a series. That will work best with the way that I'm dealing with database objects in the UI.```

Sure @robintw, we can remove ```series_exercises``` table and refer series_id in exercises table. @IanMayo, do you have any comments here?

```My next question is about why we need both serial_participants and exercise_participants```

They were originally named "*Exercise Participa***nts**" and "*Serial Participa***tion**". The latter was renamed as requested by @IanMayo. I was [checking with him](https://github.com/debrief/pepys-import/issues/839#issuecomment-812646874) if we would still want to go ahead with this change. Referring to [the long form design](https://github.com/debrief/pepys-import/issues/839#issuecomment-812063050), the **"Exercise Participants"** contains the set of platforms earmarked for this exercise. When analysts need to mark any platform against a serial, the platform dropdown element (or UI filter) will be populated from this set instead of displaying the entire platforms defined in **pepys."Platforms"** table. This approach also handles scenario where a platform couldn't take part in any of the serials (due to technical or other issues), but our reports can pull out all earmarked platforms for the given exercise.

```Why would there be more than one entry in Serial Participants? Is that just if it is active for various distinct time periods? (eg. 09:00-11:00 and then 15:00-18:00) - I don't know whether this actually happens - @IanMayo, is this something we need to support?```

Could see from [point 1 in this comment](https://github.com/debrief/pepys-import/issues/828#issuecomment-806023720) that this might be possible. Anyways, the design can handle multiple participation in a single serial. I was just informing @IanMayo that renaming **"Serial Participation"** to **"Serial Participants"** would be confusing for so and so reasons.

```Just as a final comment: it might be useful to extend the SQLFiddle a bit to include some more entries in the data so we can see more easily how this works for various more complex situations. For example, adding an exercise that has no series, adding multiple platforms assigned to different exercises/serials, with different durations etc.```

Sure thing @robintw, I'll get started on that once the design is a little stable.

**Comment by IanMayo** [comment] 2021-04-06 11:40
Hello @robintw & @arunlal-v 

## Platform participates in a serial multiple times.
I checked with the users. No, this doesn't happen.

## Two sets of participants (participations)
I think the root cause to needing two tables of participation is that we've separated the 3 tiers of `Tasks` into `Series`, `Exercises` and `Serials`.  Once we separate `Exercises` and `Serials` we need two different tables to record participations in each one. There are merits to separating the two tables, since more detail is captured at the `Serial` level.

A platform first gets assigned to an Exercise (Exercise_Participants) and then to a child serial (Serial_Participants).  The presence of a `Exercise_Participant` in a `Serial_Participant` is how we ensure a serial participant is already present in the exercise.  We currently enforce this through Python logic, but the above ensure the logic is enforced in the database, too.

## Exercises not part of a Series
I'm happy for the users to an `Other` Series, into which ad-hoc exercises are stored.  If it becomes unweildy they have the tools to separate `Other` down further - either by year or exercise type. That's their core housekeeping responsibility.

So, we do not need an `Exercise Series` table.

The above logic also keeps @robintw 's task table in the UI logical - since every exercise sits within a Series.

**Comment by arunlal-v** [comment] 2021-04-06 11:51
Thanks @IanMayo. I'll share the updated design in sometime.

**Comment by arunlal-v** [comment] 2021-04-06 12:25
Here's the [SQLFiddle with updated design](http://sqlfiddle.com/#!17/c4eb0/1)

Here's the ER Diagram.

![image](https://user-images.githubusercontent.com/77854924/113710124-f3bd5d80-9700-11eb-92c6-7e7139a53387.png)

@IanMayo, do we need **privacy_id** field added for all these tables?

**Comment by IanMayo** [comment] 2021-04-06 13:09
## Privacy Fields.

Yes, we'll need `Privacy` for all of them, please.

@robintw  - in the UI, by default we can use the lowest level value in the `Privacies` table, and not force the user to select a value.

**Comment by robintw** [comment] 2021-04-06 13:11
@IanMayo Do we definitely need a privacy for _all_ of those tables? Or just for Exercises, Series and Serials? Given that Platforms have their own privacy - can the participants tables do without a privacy?

**Comment by IanMayo** [comment] 2021-04-06 13:20
Hello @robintw  - I welcome you testing the logic.  In this instance there may be a justification.

Let's imagine HMS Queen Elizabeth (QE).  

![image](https://user-images.githubusercontent.com/1108513/113716998-104a9d00-96e3-11eb-9a92-3a630fdb8033.png)


The fact she exists is public knowledge.  The fact she is taking part in JW 21/01 is sensitive until it is published by the MOD.  So, that means the "Exercise participant" value for QE/JW21/01 is "Private" until the date of the news release when it becomes "Public".  Some of the Serials in JW21/01 may be public, since the MoD may have had to send out messages to fishing craft / aircraft about if there is going to be some GPS Jamming (for instance).  But, others won't be shared, nor will the details of who is taking part in which serials.

The above is quite a bit of juggling, but it's quite familiar to the analysts.

**Comment by robintw** [comment] 2021-04-06 13:25
Your example makes sense - lets go forward with privacies for everything.

**Comment by arunlal-v** [comment] 2021-04-06 13:56
Okay @robintw, @IanMayo.

Any other fields to be added?

**Comment by IanMayo** [comment] 2021-04-06 14:02
Here is the schema:
![image](https://user-images.githubusercontent.com/1108513/113722748-a1704280-96e8-11eb-97e7-4ffbd8213fab.png)

We need `environment` and `location` for `Serials`, we need `Force` for `Serial_Participants`

**Comment by arunlal-v** [comment] 2021-04-06 14:03
Sure @IanMayo. Will include these fields.
Also, the new **default data state** in **pepys."PlatformTypes"** and **frequency** in **pepys."Series"** are [**interval** datatypes](https://www.postgresql.org/docs/10/datatype-datetime.html#DATATYPE-INTERVAL-INPUT). We don't have that in *SQLite*.

**Comment by IanMayo** [comment] 2021-04-06 14:05
How about `DefaultDataIntervalSecs` as an integer?

**Comment by arunlal-v** [comment] 2021-04-06 14:06
We'll also be needing another field to hold units (seconds/minutes etc) or handle everything as seconds and go with only one field.

**Comment by arunlal-v** [comment] 2021-04-06 14:10
```default_data_interval_secs``` will be descriptive and preferred SQL way.

**Comment by arunlal-v** [comment] 2021-04-06 14:14
To be consistent with the other tables, I'll be going with [camelCase naming](https://en.wikipedia.org/wiki/Camel_case) for table names.

**Comment by arunlal-v** [comment] 2021-04-06 14:35
@IanMayo, what should be the datatype for start and end. Should we retain it as "Timestamp without timezone" or follow [Postgres recommendation](https://github.com/debrief/pepys-import/issues/745#issuecomment-768469517)?

**Comment by IanMayo** [comment] 2021-04-06 14:46
While data may come from different timezones, all systems capturing maritime data run at UTC, which effectively makes the TimeZone of no value.

There may be an argument in the future for changing to allow TimeZone, but this issue isn't a sufficient reason to move away from what's followed in the rest of Pepys database.

**Comment by arunlal-v** [comment] 2021-04-06 14:48
Fine

**Comment by arunlal-v** [comment] 2021-04-06 15:02
Here's the [updated sqlFiddle](http://sqlfiddle.com/#!17/5d55df/1)

Here's the ER diagram.

![image](https://user-images.githubusercontent.com/77854924/113732277-1490ad80-9717-11eb-8e01-377ee02dd4ca.png)

**Comment by IanMayo** [comment] 2021-04-06 15:13
Sorry I didn't mention this earlier @arunlal-v  - we don't need `fruqency_days` in `Series`.  It doesn't bring any value to the users.

**Comment by arunlal-v** [comment] 2021-04-06 15:17
No issues @IanMayo 

Here's the [updated  SqlFiddle](http://sqlfiddle.com/#!17/875ecc/1)

And here's the ER Diagram.

![image](https://user-images.githubusercontent.com/77854924/113734806-460a7880-9719-11eb-881b-c26bb75f7036.png)

**Comment by arunlal-v** [comment] 2021-04-06 17:25
@IanMayo, I'm guessing the answer for my following question is "No". But just wanted to get it confirmed by you.

There will be **only one** serial happening at any given time for a exercise, right?

**Comment by arunlal-v** [comment] 2021-04-06 17:27
And should we consider multiple serials in a day?

**Comment by IanMayo** [comment] 2021-04-06 18:00
There will typically be up to 5 serials per day.

The serials can overlap, though a participant can only be in one serial at a time.

While the "big players" may all do a fast-paced one-hour serial where the aircraft carrier gets attacked by aircraft, some other units may be doing a 6 hour serial that involves a slower paced undertaking such as a commando reconnaissance patrol.

**Comment by robintw** [comment] 2021-04-07 16:11
@IanMayo You said:

> I'm happy for the users to an Other Series, into which ad-hoc exercises are stored. If it becomes unweildy they have the tools to separate Other down further - either by year or exercise type. That's their core housekeeping responsibility.

I agree, that will be very helpful for me from the UI perspective. Should we create this `Other` series as part of the default metadata that can be added when the database is created? Then we can always assume it exists, and add things to it if necessary.

**Comment by IanMayo** [comment] 2021-04-07 16:18
I don't think we need to create the `Other` series.  The users can create their own top-level series - and add wargames to it.

> and add things to it if necessary.

I can only picture Pepys adding wargames to a series by a user first selecting the series (maybe after creating it), and then adding the wargame.

**Comment by arunlal-v** [comment] 2021-04-09 01:54
@IanMayo, I believe we'll be needing one or more of the following fields in **pepys."Serials"**. Kindly confirm.

**base_identifier text** - *to capture J in **J**05324* 
**day_of_month integer** - *to capture 05 in J**05**324*
**serial_index integer** - *to capture 324 in J05**324***

In the dashboard picture shared in [issue 840](https://github.com/debrief/pepys-import/issues/840), I see the serial name as **CASEX 324**, where as in the examples you have shared as comments in other replies in the same issue has **J05324**.

**Comment by arunlal-v** [comment] 2021-04-09 02:01
@IanMayo, with reference to [this comment](https://github.com/debrief/pepys-import/issues/839#issuecomment-816345745), what serial name should the dashboard display if there are multiple serials for the previous day?

**Comment by IanMayo** [comment] 2021-04-09 06:53
> @IanMayo, I believe we'll be needing one or more of the following fields in **pepys."Serials"**. Kindly confirm.
No, these serial values are human generated.

There are two names for a Serial.  The `J06230` is a human-created value that is used to uniquely refer to each part of the wargame.  The `CASEX 324` is the name of a pre-scripted _exercise_ contained in a book held by the participants.  The `CASEX 324` may occur several times across the wargame.  So, it's useful for the participant to know what they're going to be doing, but doesn't uniquely identify a serial/segment/component.

That is why both are needed, and why analysts find the `CASEX 324` field useful in addition to the exercise.

Here is where @robintw  added the `Exercise` field:
https://github.com/debrief/pepys-import/issues/836

**Comment by IanMayo** [comment] 2021-04-09 07:15
> @IanMayo, with reference to [this comment](https://github.com/debrief/pepys-import/issues/839#issuecomment-816345745), what serial name should the dashboard display if there are multiple serials for the previous day?

The `Serial` (J06230) will always be displayed - since they are unique for this wargame. But, analysts will find value in the `exercise` label too (CASEX 324) - so we'll display both.

**Comment by IanMayo** [comment] 2021-04-09 07:24
Aah, @arunlal-v - I realise we need another field for `SerialParticipants`.  The participant will be playing as either `Blue Force` (friendly) or `Red Force` (enemy).  One day we may need to support `White Force` (non-combatant).

I think this could be met through a `Force Types` table, containing:
* ForceID
* Name (Blue or Red to start with)
* Color (#00F or #F00 to start with)

This will allow a compulsory `Force` field in the `SerialParticipants` table.

**Comment by arunlal-v** [comment] 2021-04-09 07:27
> > @IanMayo, with reference to [this comment](https://github.com/debrief/pepys-import/issues/839#issuecomment-816345745), what serial name should the dashboard display if there are multiple serials for the previous day?
> 
> The `Serial` (J06230) will always be displayed - since they are unique for this wargame. But, analysts will find value in the `exercise` label too (CASEX 324) - so we'll display both.

**Comment by IanMayo** [comment] 2021-04-09 07:40
> What will happen if the query finds two Serials (say J06230 and J06240) happened on the day before?

The 06 indicates it's a serial on the 6th day of the month.  Serials the previous day would be `J05xxx`.

**Comment by robintw** [comment] 2021-04-09 07:44
@IanMayo I'll go ahead and do these changes in the SQLAlchemy table definitions (I've started creating those, so they can run in parallel with this discussion, and I can get on with updating the UI to use the new tables).

For the new `ForceTypes` table, should we populate it with the Blue and Red entries when we do the `populate reference data` action?

**Comment by IanMayo** [comment] 2021-04-09 08:30
> Populate Reference data
I wish I'd thought of that :-)

Great idea.

**Comment by robintw** [comment] 2021-04-09 12:39
@IanMayo I've just removed the old Tasks and Participants tables. In the `Geometries` table we currently have a foreign key to `Tasks.task_id`. What do you want that replaced with? A reference to `Series`, `Wargames` or `Serials`? I'm guessing `Serials` but wanted to check.

**Comment by IanMayo** [comment] 2021-04-09 12:49
`geometries - task_id`
Well, that's a blast from the past. I guess the intention was to allow the bounding rectangle for an exercise to be represented.

Yes, let's allow a reference to a `serial_id`

**Comment by robintw** [comment] 2021-04-09 13:07
Great thanks.

A couple of things to check @IanMayo:
1. Are `start` and `end` required fields for both `Wargame` and `Serial`?
2. Are `start` and `end` optional for both SerialParticipant and WargameParticipant, or are they required for a Wargame?
3. Is the `Serial.exercise` field optional?

**Comment by IanMayo** [comment] 2021-04-09 13:22
Hi,
1. Hmm, I don't think they are _essential_ for our logic, but let's say "Yes" - just to make it most likely that we have the data we need.
2. They are optional for participants. When missing, we know it's the extent of the wargame/serial.
3. Yes - it is not always present.

**Comment by robintw** [comment] 2021-04-09 13:25
Thanks.

Ah, just realised I asked the question partly incorrectly. Currently we don't have a `start` and `end` field for `WargameParticipants` but we do for `SerialParticipants`. That is, we just add participants to the Wargame with no information on _when_ they are taking part, and that information on _when_ comes as part of the `SerialParticipant`. Is that correct?

**Comment by IanMayo** [comment] 2021-04-09 13:30
Hmm, at this point in time it's not important. We _could_ help the user be restricting serial participation times to the overall war-game participation time.  But, that's not an important capability.

Let's skip start/end date for war-game participation until we have a stronger use case.

**Comment by robintw** [comment] 2021-04-09 13:34
Excellent, that was the answer I was hoping you'd give :)

@IanMayo @arunlal-v: Are we fairly sure that we've finalised the database structure for the new tables? If so, I'll go ahead and create the database migration for the new structure. The GUI is progressing, but for Ian to test it I'll need to have the migration sorted.

(@IanMayo: I think I've got most of the existing Tasks GUI working with the new tables, and I've added validation. I expect you'll be able to find some bugs, but don't try to test it yet until I've dealt with the database migration. I'm on childcare duty now, but will aim to do a bit more over the weekend (if I have time), otherwise I'll continue on Monday morning).

**Comment by IanMayo** [comment] 2021-04-09 13:57
That's fine - thanks @robintw .

I'm not aware of any table changes - other than the `Force` one that you're aware of.

**Comment by arunlal-v** [comment] 2021-04-09 15:37
>[We will have one coverage diagram per serial.](https://github.com/debrief/pepys-import/issues/840#issuecomment-816502452)

This answers my question ```What will happen if the query finds two Serials (say J06230 and J06240) happened on the day before?```. I was under the impression that the dashboard will have only one diagram for all serials. Thanks @IanMayo.

**Comment by IanMayo** [comment] 2021-04-09 15:38
* One diagram per serial
* All of yesterday's serials on page (multiple diagrams)

Mockup:

**Comment by arunlal-v** [comment] 2021-04-09 15:42
Thanks a lot @IanMayo. This makes it much clearer.

I don't see a need for the second query being called multiple times. I mean that's a call we can take later based on performance. Right now, the second query can handle all serials at once.

**Comment by IanMayo** [comment] 2021-04-09 15:47
* multiple times

If Each SuperSet component makes its own connection to the database, then the app will end up calling the query multiple times - either once per Serial or even once per platform.

Note: I'm currently considering getting a custom (temporary) Python visualisation setup, just to get something working. Once this wargame is over - we can learn lessons to pass onto SuperSet.

For this hand-made Python visualisation it's quite likely that we can just run the query once - for all the data, then slice it up before being rendered.

**Comment by arunlal-v** [comment] 2021-04-09 15:50
Sure @IanMayo. 

@robintw 

These 2 items are pending on the schema front. Working on them right now.

1)
	Based on the above, I think we need @arunlal-v to modify the table design:

	Rename exercises to wargames
	Rename serial.name to serial.serial_number and introduce an optional exercise text field.
2)
	ah, @arunlal-v - I realise we need another field for SerialParticipants. The participant will be playing as either Blue Force (friendly) or Red Force (enemy). One day we may need to support White Force (non-combatant).

	I think this could be met through a Force Types table, containing:

	ForceID
	Name (Blue or Red to start with)
	Color (#00F or #F00 to start with)
	This will allow a compulsory Force field in the SerialParticipants table.

**Comment by arunlal-v** [comment] 2021-04-09 17:19
@robintw, below is the updated script incorporating the comments in this thread.
```SQL
--drop objects

drop table if exists pepys."SerialParticipants";
drop table if exists pepys."Forces";
drop table if exists pepys."WarGameParticipants";
drop table if exists pepys."Serials";
drop table if exists pepys."WarGames";
drop table if exists pepys."Series";

--Create "Series"
create table pepys."Series"(
	series_id uuid constraint serpk primary key,
	name text,
	privacy_id uuid constraint serprvref references pepys."Privacies"(privacy_id)
);

--Create "WarGames"
create table pepys."WarGames"(
	wargame_id uuid constraint wrgmpk primary key,
	name text,
	series_id uuid constraint seridref references pepys."Series"(series_id),
	start timestamp without time zone,
	"end" timestamp without time zone,
	privacy_id uuid constraint exerprvref references pepys."Privacies"(privacy_id)
);

--Create "Serials"
create table pepys."Serials"(
	serial_id uuid constraint gampk primary key,
	wargame_id uuid constraint serwgidref references pepys."WarGames"(wargame_id),
	serial_number text,
	exercise text,
	start timestamp without time zone,
	"end" timestamp without time zone,
	environment text,
	location text,
	privacy_id uuid constraint serprivref references pepys."Privacies"(privacy_id)
);

--Create "WarGameParticipants"
create table pepys."WarGameParticipants"(
	wargame_participant_id uuid constraint partpk primary key,
	wargame_id uuid constraint exprtwgidref references pepys."WarGames"(wargame_id),
	platform_id uuid constraint pltref references pepys."Platforms"(platform_id),
	privacy_id uuid constraint exprtprvref references pepys."Privacies"(privacy_id)
);

--Create "Forces"
drop table if exists pepys."Forces";
create table pepys."Forces"(
	force_id uuid constraint foridpk primary key,
	name text constraint namenotnull not null,
	color text
);

--Create "SerialParticipants"
create table pepys."SerialParticipants"(
	serial_participant_id uuid constraint spartid primary key,
	wargame_participant_id uuid constraint partref references pepys."WarGameParticipants"(wargame_participant_id),
	serial_id uuid constraint serref references pepys."Serials"(serial_id),
	start timestamp without time zone,
	"end" timestamp without time zone,
	force uuid constraint foridrf references pepys."Forces"(force_id),
	privacy_id uuid constraint serprtprvref references pepys."Privacies"(privacy_id)
);

alter table pepys."PlatformTypes" add column default_data_interval_secs integer;

--populate data

update pepys."PlatformTypes" set default_data_interval_secs = 30;

insert into pepys."Series" values ('1e0187ca-9146-0794-62fb-c6f1c69c3dee', 'Suez Warriors', '225f3795-56c7-43c0-9846-ae6a3a6ce0fe');

insert into pepys."WarGames" values ('7d5a71e7-40ad-06e0-99f9-513b3216ed73', 'SW 20/01', '1e0187ca-9146-0794-62fb-c6f1c69c3dee', '2020-11-15 00:00:00.000000','2020-11-15 23:59:59.000000', '225f3795-56c7-43c0-9846-ae6a3a6ce0fe');

insert into pepys."Serials" values ('faa18ef7-6823-33dc-0f16-de6e4b2c02f3','7d5a71e7-40ad-06e0-99f9-513b3216ed73','SW05110', 'Exercise', '2020-11-15 00:00:00.000000','2020-11-15 23:59:59.000000', 'Environment', 'Location', '225f3795-56c7-43c0-9846-ae6a3a6ce0fe');

insert into pepys."WarGameParticipants" values ('f16e405b-5f3a-f4e2-50e2-e5a5dabdf142','7d5a71e7-40ad-06e0-99f9-513b3216ed73','50d64387-9f91-4c6f-8933-f4e7b1a7d8ab','225f3795-56c7-43c0-9846-ae6a3a6ce0fe');

insert into pepys."Forces" values ('225f3795-56c7-43c0-9846-ae6a3a6ce0ff','Blue','#F00');

insert into pepys."SerialParticipants" values ('cae20db7-ab15-8ba1-eeaa-fc7cbdc172d7','f16e405b-5f3a-f4e2-50e2-e5a5dabdf142','faa18ef7-6823-33dc-0f16-de6e4b2c02f3', '2020-11-15 00:00:00.000000','2020-11-15 23:59:59.000000', '225f3795-56c7-43c0-9846-ae6a3a6ce0ff', '225f3795-56c7-43c0-9846-ae6a3a6ce0fe');

commit;
```

**Comment by arunlal-v** [comment] 2021-04-10 16:54
@robintw, just FYI. The constraint names given for the new tables do not follow the same syntax or pattern as the existing ones.

**Comment by robintw** [comment] 2021-04-10 17:48
That's fine @arunlal-v - I've been translating everything into the relevant SQLAlchemy table definitions, so the database migration will pick up our standard of constraint naming from our configuration. I'll get the migration done on Monday.

**Comment by robintw** [comment] 2021-04-12 08:32
Hi @arunlal-v @IanMayo.

I've now added the database migration scripts in my PR at #833. @IanMayo, if you want to test the new GUI then you should be able to checkout that branch and run it through Pepys Admin. You'll need to run a database migration first.

I see that @arunlal-v has already added these tables to the TracStor database. Are you ok if we delete these, and then run the migration on that database? There will be some subtle differences between the SQL you ran to create these tables, and the SQL that the migration will run (eg. constraint names, string field lengths etc) and the migration code is likely to get confused if it doesn't have everything exactly how it expects to see it. We can then add the test data again if necessary.

Also, my SQLAlchemy scripts and migrations were already set up to call the table `Wargames` rather than `WarGames` (as I believe it is usually treated as a single word). I'd have to change a lot of stuff to make it `WarGames`(and I tried to do a simple find and replace and it caused more problems than it solved), so can we keep it as `Wargames`? That may require some changes in your queries that look for Serials in the previous day and then get the coverage.

**Comment by IanMayo** [comment] 2021-04-12 08:51
> delete tables
Yes - that sounds the right thing to do.

> table name
Yes - let's stick with Wargames

**Comment by robintw** [comment] 2021-04-12 08:58
Ok, I'll wait for confirmation from @arunlal-v that he's ok for me to delete the tables, then I'll go ahead and delete them (or he can delete them if he prefers - as he knows exactly what he created)

**Comment by arunlal-v** [comment] 2021-04-12 13:37
Hey @robintw, sure. Please go ahead. 

This is my summary.

Tables created: 

pepys."SerialParticipants";
pepys."Forces";
pepys."WarGameParticipants";
pepys."Serials";
pepys."WarGames";
pepys."Series";

Tables altered:

pepys."PlatformTypes";

**Comment by robintw** [comment] 2021-04-12 16:26
Thanks @arunlal-v.

I've deleted the tables and run the migration on the TracStor database. Everything should be working now - I've added a few example Series/Wargames/Serials, although no participants yet (as I haven't got the GUI for that bit done yet...that's tomorrow's job).

As well as the replacement of `WarGames` with `Wargames`, I think there may also be a difference with the `Forces` table - in my version it is `ForceTypes` (to match up with all the other `XXXTypes` tables that we have).

Let me know if you have any difficulties.

**Comment by arunlal-v** [comment] 2021-04-12 18:56
Sure @robintw. 

I was checking with @IanMayo the other day on **pepys."ForceTypes"** table. Shouldn't it be **pepys."Forces"**? That should be in line with **pepys."Platforms"** and **pepys."PlatformTypes"** tables.

**Comment by robintw** [comment] 2021-04-12 19:02
Umm, I'll let @IanMayo confirm what he wants: but in my view it counts as one of the group of tables that we refer to as a 'Reference Table' and a lot of those are `XXXType`.

(It would be a bit of a pain to change this now, but definitely far less of a pain to change it now than it would be to change it later - so if we're going to change it, we should change it now)

Also, @IanMayo: How should we go about pre-populating the ForceTypes table with Red/Blue entries? We can load these from CSVs, but we may run into the same problem as we discussed in relation to adding `default_data_interval_secs`: the users might not want to import from CSVs again as they might import a load of other stuff they don't want (although there is a command-line option to import from a specific folder, so they could use that - but that requires them running Pepys command lines).

**Comment by IanMayo** [comment] 2021-04-12 19:35
There are pros for both options:
1. The "Reference" tables tend to be Types of data
2. This is a list of forces, not a list of types of force.

> bit of a pain to change this now.

Let's totally stick with ForceTypes then :-)

**Comment by robintw** [comment] 2021-04-29 07:58
These tables are now all implemented in SQLAlchemy and used in Pepys.

**Closed by robintw** 2021-04-29 07:58 UTC
Labels: question
